sudo: required
services:
  - docker

before_install:
  - gem update bundler
  - docker build -t marcellm/docker-react -f Dockerfile.dev .

script:
  - docker run marcellm/docker-react npm run test -- --coverage